### ISSUE TITLE
Connect2@bluenetwerk33.ca

### ISSUE THREAD

**Issue by hunksd6** [Azure/aks-periscope#116]
![1280px-Publishing_Company_Network_Diagram.png.jpg](https://user-images.githubusercontent.com/72580721/133132959-1b616a10-e2a8-415b-bca6-b36fe7bbb956.jpg)

**Comment by Tatsinnit** [comment]
Thank you @hunksd6 - what is the purpose and context of this issue? Is it missing details? Thanks.

* You have already opened another one here as New Azure Repository #112 along with #113 and #115 as well, which also seems empty workitem with no information. Thanks
* since this is the 4th in last 4 days with no further information I will close all these for now, unless more information is added. Thanks.

Thanks and cc: @rzhang628 , @qpetraroia and @arnaud-tincelin
