### ISSUE TITLE
Blob with logs is not getting created with az aks kollect command

### ISSUE THREAD

**Issue by monubamb** [Azure/aks-periscope#12]
Even though the command to collect logs succeeded, I dont see the aforementioned blob created with logs.

Deploying aks-periscope

Your logs are being uploaded to storage account activateazure2diag

**You can download Azure Stroage Explorer here https://azure.microsoft.com/en-us/features/storage-explorer/ to check the logs by adding the storage account using the following URL:
https://activateazure2diag.blob.core.windows.net/aksaspen2-dns-22701a84-hcp-eastus2-azmk8s-io?sv=2019-02-02**

But there is no blob created. Any idea?

**Comment by Tatsinnit** [comment]
Hiya, @monubamb 

I am able to replicate this with consistency. This question is not answered for a while, possibly adding more context at the tool level which will help in digging deeper.

**Possible explanation what is happening:** 

* I think this is happening due to underlying cli and ARM based requirement for `storageaccount` where `storagename needs to be between 3-24 character long`. more details here. https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/error-storage-account-name 

**Underlying storage account** 

* In your specific case if you check your storage you will see logs uploaded under the blob container: `aksaspen2-dns-22701a84` and not `aksaspen2-dns-22701a84-hcp-eastus2-azmk8s-io`  

**Possible fix** is to actually fix the underlying mechanism to generate the right download link for storage.

I will see if this can be tagged for workitem around it.

Thanks,
^Tats
